import { passThrough } from './utils.js'

passThrough(String, ['fromCharCode', 'fromCodePoint', 'raw'])

passThrough(String.prototype, [
    'at',
    'charAt',
    'charCodeAt',
    'codePointAt',
    'concat',
    'endsWith',
    'includes',
    'indexOf',
    'lastIndexOf',
    'localeCompare',
    'match',
    'matchAll',
    'normalize',
    'padEnd',
    'padStart',
    'repeat',
    'replace',
    'replaceAll',
    'search',
    'slice',
    'split',
    'startsWith',
    'substr',
    'substring',
    'toLocaleLowerCase',
    'toLocaleUpperCase',
    'toLowerCase',
    'toString',
    'toUpperCase',
    'trim',
    'trimEnd',
    'trimLeft',
    'trimRight',
    'trimStart',
    'valueOf',
])
