export enum SkinSprite {
    NoteHeadBase = 1000,
    NoteHeadRed,
    NoteHeadGreen,
    NoteHeadBlue,
    NoteHeadYellow,
    NoteHeadPurple,
    NoteHeadCyan,

    NoteTickBase = 2000,
    NoteTickRed,
    NoteTickGreen,
    NoteTickBlue,
    NoteTickYellow,
    NoteTickPurple,
    NoteTickCyan,

    NoteTailBase = 3000,
    NoteTailRed,
    NoteTailGreen,
    NoteTailBlue,
    NoteTailYellow,
    NoteTailPurple,
    NoteTailCyan,

    NoteConnectionBase = 11000,
    NoteConnectionRed,
    NoteConnectionGreen,
    NoteConnectionBlue,
    NoteConnectionYellow,
    NoteConnectionPurple,
    NoteConnectionCyan,

    SimultaneousConnectionBase = 12000,
    SimultaneousConnectionRed,
    SimultaneousConnectionGreen,
    SimultaneousConnectionBlue,
    SimultaneousConnectionYellow,
    SimultaneousConnectionPurple,
    SimultaneousConnectionCyan,

    DirectionalMarkerBase = 21000,
    DirectionalMarkerRed,
    DirectionalMarkerGreen,
    DirectionalMarkerBlue,
    DirectionalMarkerYellow,
    DirectionalMarkerPurple,
    DirectionalMarkerCyan,

    SimultaneousMarkerBase = 22000,
    SimultaneousMarkerRed,
    SimultaneousMarkerGreen,
    SimultaneousMarkerBlue,
    SimultaneousMarkerYellow,
    SimultaneousMarkerPurple,
    SimultaneousMarkerCyan,

    StageMiddle = 40000,

    StageLeftBorder = 40001,
    StageRightBorder = 40002,
    StageTopBorder = 40004,
    StageBottomBorder = 40008,

    StageTopLeftCorner = 40005,
    StageTopRightCorner = 40006,
    StageBottomLeftCorner = 40009,
    StageBottomRightCorner = 40010,

    Lane = 40100,
    JudgmentLine = 41000,
    NoteSlot = 41001,
    StageCover = 42000,
}
